"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "../../ui/SiteLink";
type RequestData = { id: string; category: string; location: string; neededBy: string; description: string; budget: string; priceType: string; customerName: string; phone: string; email: string; status: string; expiresAt: number; responders: {id:string;company_name:string;accessed_at:number}[] };
export function RequestManager({ id }: { id: string }) {
  const [token, setToken] = useState(""); const [data, setData] = useState<RequestData | null>(null); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [message, setMessage] = useState("");
  useEffect(() => { const value = new URLSearchParams(window.location.hash.slice(1)).get("token") || ""; setToken(value); if (!value) { setState("error"); return; } fetch(`/api/requests/${id}/manage`, { headers: { "x-management-token": value } }).then(async response => { if (!response.ok) throw new Error(); setData(await response.json() as RequestData); setState("ready"); }).catch(() => setState("error")); }, [id]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await call(Object.fromEntries(new FormData(event.currentTarget).entries())); setMessage(response.ok ? "Změny jsou uložené." : "Změny se nepodařilo uložit."); }
  async function action(name: "close" | "extend") { if (name === "close" && !window.confirm("Opravdu chcete poptávku ukončit? Dodavatelé ji už neuvidí.")) return; const response = await call({ action: name }); if (!response.ok) return setMessage("Akci se nepodařilo dokončit."); const body = await response.json() as { status?: string; expiresAt?: number }; setData(current => current ? { ...current, status: body.status || current.status, expiresAt: body.expiresAt || current.expiresAt } : current); setMessage(name === "close" ? "Poptávka je ukončená." : "Poptávka byla prodloužena o 30 dní."); }
  function call(body: object) { return fetch(`/api/requests/${id}/manage`, { method: "PATCH", headers: { "content-type": "application/json", "x-management-token": token }, body: JSON.stringify(body) }); }
  async function review(event:FormEvent<HTMLFormElement>,supplierId:string){event.preventDefault();const form=event.currentTarget;const response=await fetch("/api/reviews/supplier",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(new FormData(form)),requestId:id,supplierId,managementToken:token})});const body=await response.json() as {error?:string};setMessage(response.ok?"Děkujeme, hodnocení bylo uloženo.":body.error||"Hodnocení se nepodařilo uložit.");if(response.ok)form.reset()}
  if (state === "loading") return <main className="manage-request status-card"><h1>Načítám poptávku…</h1></main>;
  if (state === "error" || !data) return <main className="manage-request status-card"><p className="eyebrow">SOUKROMÁ SPRÁVA</p><h1>Odkaz není platný</h1><p>Zkontrolujte, že jste otevřeli celý odkaz včetně části za znakem #. Pokud jste jej ztratili, obraťte se na podporu.</p><Link className="primary" href="/dodavatele">Zadat novou poptávku</Link></main>;
  return <><header className="site-header"><Link href="/" className="brand"><span>JdemNa</span><strong>To!</strong></Link><nav><Link href="/">Hlavní stránka</Link></nav></header><main className="manage-request"><section className="manage-head"><p className="eyebrow">SOUKROMÁ SPRÁVA POPTÁVKY</p><h1>Vaše poptávka</h1><div className={`request-status ${data.status}`}>{data.status === "active" ? "Aktivní" : "Ukončená"} · platnost do {new Date(data.expiresAt).toLocaleDateString("cs-CZ")}</div></section><form onSubmit={save}>
    <label>Obor *<input required name="category" defaultValue={data.category}/></label><label>Popis zakázky *<textarea required minLength={20} name="description" defaultValue={data.description}/></label><div className="form-row"><label>Adresa nebo místo *<input required name="location" defaultValue={data.location}/></label><label>Potřebuji do *<input required type="date" name="neededBy" defaultValue={data.neededBy}/></label></div><div className="form-row"><label>Rozpočet<input name="budget" defaultValue={data.budget}/></label><label>Způsob nacenění<input name="priceType" defaultValue={data.priceType}/></label></div><fieldset><legend>Kontakt</legend><div className="form-row"><label>Jméno *<input required name="customerName" defaultValue={data.customerName}/></label><label>Telefon *<input required name="phone" defaultValue={data.phone}/></label></div><label>E-mail *<input required type="email" name="email" defaultValue={data.email}/></label></fieldset>
    {message && <p className="manage-message" role="status">{message}</p>}<div className="manage-actions"><button className="primary" type="submit">Uložit změny</button><button className="ghost" type="button" onClick={() => action("extend")}>Prodloužit o 30 dní</button>{data.status === "active" && <button className="danger" type="button" onClick={() => action("close")}>Ukončit poptávku</button>}</div>
  </form>{data.responders?.length>0&&<section className="request-responders"><h2>Kdo si zobrazil váš kontakt</h2><p>Po dokončení můžete dodavatele jednou ohodnotit. Hodnocení ovlivní pořadí ve veřejném seznamu.</p>{data.responders.map(s=><form key={s.id} onSubmit={e=>review(e,s.id)}><b>{s.company_name}</b><select required name="rating" defaultValue=""><option value="" disabled>Vyberte hodnocení</option><option value="5">5 – výborné</option><option value="4">4 – velmi dobré</option><option value="3">3 – dobré</option><option value="2">2 – slabé</option><option value="1">1 – špatné</option></select><input name="comment" maxLength={1200} placeholder="Krátká zkušenost (volitelné)"/><button className="primary">Odeslat</button></form>)}</section>}<p className="privacy-note">Tato stránka je přístupná jen přes váš soukromý odkaz. JdemNaTo! nevstupuje do dohody, ceny ani platby mezi vámi a dodavatelem.</p></main></>;
}
