export const categories = [
  ["Administrativa", "Asistent, back office, recepce"], ["IT a technologie", "Vývoj, data, podpora, bezpečnost"], ["AI a automatizace", "AI specialista, automatizace, anotace"], ["Elektro", "Elektrikář, servis, fotovoltaika"], ["Stavebnictví", "Zedník, stavbyvedoucí, projektant"], ["Výroba", "Operátor, kontrola kvality, mistr"], ["Strojírenství", "CNC, konstruktér, svářeč"], ["Automotive", "Výroba, servis, diagnostika"], ["Řemesla", "Instalatér, truhlář, malíř"], ["Doprava a logistika", "Řidič, kurýr, dispečer"], ["Sklady", "Skladník, VZV, expedice"], ["Obchod", "Prodej, nákup, key account"], ["Marketing", "Obsah, PPC, sociální sítě"], ["Zákaznická péče", "Podpora, klientský servis"], ["Gastronomie", "Kuchař, číšník, barista"], ["Hotely a cestovní ruch", "Recepce, provoz, průvodce"], ["Zdravotnictví", "Sestra, lékař, laborant"], ["Sociální služby", "Pečovatel, sociální pracovník"], ["Školství", "Učitel, lektor, vychovatel"], ["Finance a účetnictví", "Účetní, analytik, mzdy"], ["Právo", "Právník, koncipient, compliance"], ["Reality", "Makléř, správa nemovitostí"], ["Bezpečnost", "Ostraha, BOZP, hasiči"], ["Úklid", "Úklid domácností a provozů"], ["Zemědělství", "Pěstitelství, chov, lesnictví"], ["Energetika", "Energetik, obnovitelné zdroje"], ["Média a kreativní práce", "Grafika, video, redakce"], ["Management", "Vedoucí, projektové řízení"], ["Věda a výzkum", "Laboratoře, vývoj, výzkum"], ["Veřejná správa", "Úřady, obce, neziskový sektor"],
] as const;

export const jobs = [
  { slug:"elektrikar-pro-fotovoltaiku", title:"Elektrikář/ka pro fotovoltaiku", company:"SlunceTech s.r.o.", place:"Pardubice", pay:"45–62 000 Kč", type:"HPP · IČO", tags:["Ranní provoz", "Vhodné i pro začátečníky", "Čeština"], match:94, kind:"Práce", expires:"2026-10-15" },
  { slug:"zakaznicka-podpora-z-domova", title:"Zákaznická podpora z domova", company:"Dobrá linka s.r.o.", place:"Celá ČR", pay:"34–42 000 Kč", type:"HPP · plně z domova", tags:["Komunikace převážně písemně", "Pouze čeština"], match:91, kind:"Práce", expires:"2026-10-05" },
  { slug:"skladnik-ranni-smena", title:"Skladník/ce – ranní směna", company:"LogiMorava a.s.", place:"Olomouc", pay:"190–220 Kč/h", type:"DPP · DPČ", tags:["Ranní směna", "Vzdělání nerozhoduje"], match:87, kind:"Brigáda", expires:"2026-09-30" },
] as const;

export const gigs = [
  { title:"Kompletní elektroinstalace rodinného domu", place:"Hradec Králové", budget:"85–120 000 Kč", meta:"Elektro · realizace do 30. 10." }, { title:"Tvorba webu pro malé knihkupectví", place:"Na dálku", budget:"35–55 000 Kč", meta:"Weby · jednorázová zakázka" }, { title:"Pravidelný úklid kanceláří", place:"Praha 7", budget:"9 000 Kč / měsíc", meta:"Úklid · dlouhodobě" },
] as const;
