"use client";
import { FormEvent, useState } from "react";
type Profile=Record<string,string>|null;
const preferenceOptions=["Plně z domova","Na místě","Kombinovaně","Pružná pracovní doba","Ranní směny","Vhodné pro začátečníky","Vzdělání nerozhoduje","Pouze čeština","Komunikace písemně"];
export function CandidateProfile({email,name,profile}:{email:string;name:string;profile:Profile}){
  const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");const form=new FormData(event.currentTarget);const preferences=form.getAll("preferences").join(", ");const response=await fetch("/api/candidates/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...Object.fromEntries(form.entries()),preferences})});const body=await response.json() as {error?:string};setSaving(false);setMessage(response.ok?"Profil je uložený.":body.error||"Profil se nepodařilo uložit.")}
  const selected=(profile?.preferences||"").split(", ");
  return <main className="candidate-page"><section className="candidate-intro"><p className="eyebrow">PRO UCHAZEČE</p><h1>Řekněte, jakou práci hledáte.</h1><p>Uložte své zkušenosti, vzdělání a podmínky, které vám vyhovují. Profil můžete kdykoliv upravit.</p><div><b>{name}</b><span>{email}</span></div></section><form onSubmit={save} className="candidate-form">
    <div className="form-title"><div><p className="eyebrow">MŮJ PRACOVNÍ PROFIL</p><h2>{profile?"Upravit profil":"Vytvořit profil"}</h2></div><span>Povinná pole jsou označena *</span></div>
    <div className="profile-row"><label>Jakou pozici hledáte? *<input required name="desiredRole" defaultValue={profile?.desired_role||""} placeholder="Např. skladník, účetní, elektrikář"/></label><label>Kde chcete pracovat? *<input required name="location" defaultValue={profile?.location||""} placeholder="Např. Brno a okolí nebo celá ČR"/></label></div>
    <div className="profile-row"><label>Typ práce nebo úvazku *<input required name="workTypes" defaultValue={profile?.work_types||""} placeholder="HPP, zkrácený úvazek, brigáda, IČO…"/></label><label>Očekávaná mzda<input name="salaryExpectation" defaultValue={profile?.salary_expectation||""} placeholder="Např. od 40 000 Kč hrubého"/></label></div>
    <label>Pracovní zkušenosti *<textarea required minLength={30} name="experience" defaultValue={profile?.experience||""} placeholder="Popište předchozí pozice, hlavní činnosti, délku praxe a dosažené výsledky."/></label>
    <label>Vzdělání a odborné kurzy *<textarea required minLength={10} name="education" defaultValue={profile?.education||""} placeholder="Škola, obor, nejvyšší vzdělání, rekvalifikace nebo důležité certifikáty."/></label>
    <label>Dovednosti *<textarea required minLength={10} name="skills" defaultValue={profile?.skills||""} placeholder="Např. práce s Excelem, řidičský průkaz B, svařování, němčina B2…"/></label>
    <label>Krátce o vás<textarea name="summary" defaultValue={profile?.summary||""} placeholder="Co vám jde, co vás baví a co můžete zaměstnavateli nabídnout."/></label>
    <fieldset className="preference-box"><legend>Co vám v práci vyhovuje</legend><p>Vyberte pouze pozitivní preference. Můžete označit více možností.</p><div>{preferenceOptions.map(item=><label key={item}><input type="checkbox" name="preferences" value={item} defaultChecked={selected.includes(item)}/>{item}</label>)}</div><label>Další požadavky nebo preference<textarea name="requirements" defaultValue={profile?.requirements||""} placeholder="Např. možnost nástupu od října, pravidelná pracovní doba nebo bezbariérové pracoviště…"/></label></fieldset>
    <div className="profile-row"><label>Telefon<input type="tel" name="phone" defaultValue={profile?.phone||""} placeholder="+420 777 123 456"/></label><label>Viditelnost profilu<select name="visibility" defaultValue={profile?.visibility||"private"}><option value="private">Soukromý – vidím ho jen já</option><option value="employers">Zobrazit přihlášeným zaměstnavatelům</option></select></label></div>
    <div className="visibility-note"><strong>Profil není veřejný na internetu.</strong> Po druhé volbě jej uvidí pouze přihlášené firemní účty. Kontakt odkryjí samostatným kliknutím a přístup zaznamenáme. Viditelnost nezaručuje pracovní nabídku a můžete ji kdykoliv vypnout.</div>
    {message&&<p className="candidate-message" role="status">{message}</p>}<button className="primary candidate-save" disabled={saving}>{saving?"Ukládám…":"Uložit pracovní profil →"}</button>
  </form></main>
}
