"use client";
import Link from "./SiteLink";
import { useEffect, useState } from "react";
import { categories, gigs, jobs } from "../data";
import "../home-simplified.css";

const Brand = ({inverse=false}:{inverse?:boolean}) => <Link href="/" className={`brand ${inverse?"inverse":""}`}><span>JdemNa</span><strong>To!</strong></Link>;

export function HomePage() {
  const [prefs, setPrefs] = useState(["Plně z domova", "Vhodné pro začátečníky"]);
  useEffect(() => { const saved=localStorage.getItem("jdemnato-preferences"); if(saved)try{setPrefs(JSON.parse(saved))}catch{} }, []);
  const toggle = (p:string) => setPrefs(v => { const next=v.includes(p) ? v.filter(x=>x!==p) : [...v,p]; localStorage.setItem("jdemnato-preferences",JSON.stringify(next)); return next; });
  return <>
    <header className="site-header"><Brand/><nav><Link href="/prace">Hledám práci</Link><Link href="/dodavatele">Hledám dodavatele</Link><Link href="/registrace">Nabízím práci nebo služby</Link></nav><div className="header-actions"><Link className="ghost auth-link" href="/prihlaseni">Přihlásit se</Link><Link className="primary small auth-link" href="/registrace">Registrace</Link></div></header>
    <main>
      <div className="site-slogan">Zkušební verze zdarma pro všechny. <strong>Budoucí poplatek se bude týkat jen dodavatelů a firem.</strong></div>
      <section className="hero"><div className="hero-copy"><div className="kicker"><span/> PRÁCE · DODAVATELÉ · POPTÁVKY</div><h1>Co právě hledáte?<br/><em>Jdeme na to.</em></h1><p>Najděte si práci, zadejte poptávku dodavatelům nebo nabídněte práci a služby. Přehledně, jednoduše a napřímo.</p><div className="trust"><span>✓ Bez prostředníka</span><span>✓ Přímý kontakt</span><span>✓ Pro celou ČR</span></div><p className="app-coming"><span>APLIKACE</span> Mobilní aplikaci chystáme</p></div><div className="hero-shape"><div className="match-card"><small>JEDNO MÍSTO</small><strong>3</strong><span>jednoduché cesty</span><div className="meter"><i/></div></div><div className="orbit o1">◒ <span>Hledám práci</span></div><div className="orbit o2">⌂ <span>Hledám dodavatele</span></div><div className="orbit o3">＋ <span>Nabízím práci nebo služby</span></div></div></section>
      <section className="preferences"><Head eyebrow="CO MI VYHOVUJE" title="Hledám podle svých pravidel" copy="Vyberte pozitivně, co je pro vás důležité. Preference slouží jen vám a firmy je nevidí."/><div className="chips">{["Plně z domova","Na místě","Kombinovaně","Pouze čeština","Vhodné pro začátečníky","Vzdělání nerozhoduje","Komunikace písemně","Ranní směny","Pružná pracovní doba","Pracovní smlouva","Dohoda","Spolupráce na IČO"].map(x=><button onClick={()=>toggle(x)} className={prefs.includes(x)?"selected":""} key={x}>{prefs.includes(x)?"✓ ":"＋ "}{x}</button>)}</div><p className="preference-note">Vaše preference zůstávají pouze v tomto zařízení.</p></section>
      <section className="listings" id="nabidky"><Head eyebrow="HLEDÁM ZAMĚSTNÁNÍ" title="Aktuální nabídky práce" link="Jdu na všechny nabídky →"/><div className="job-grid">{jobs.map(j=><Link href={`/prace/${j.slug}`} className="job-card" key={j.slug}><div className="job-top"><span className="company-mark">{j.company[0]}</span><span className="match">{j.match}% shoda</span></div><small>{j.company}</small><h3>{j.title}</h3><div className="job-meta"><span>⌖ {j.place}</span><span>◷ {j.type}</span><span className="pay">{j.pay}</span></div><div className="tags">{j.tags.map(t=><span key={t}>{t}</span>)}</div><b>Jdu na nabídku →</b></Link>)}</div></section>
      <section className="gigs" id="zakazky"><Head eyebrow="HLEDÁM ZAKÁZKU" title="Nové poptávky pro dodavatele" link="Jdu na všechny zakázky →" light/><div className="gig-list">{gigs.map((g,i)=><article key={g.title}><span className="gig-no">0{i+1}</span><div><small>{g.meta}</small><h3>{g.title}</h3><p>⌖ {g.place}</p></div><strong>{g.budget}</strong><button aria-label={`Otevřít ${g.title}`}>↗</button></article>)}</div></section>
      <section className="categories" id="obory"><Head eyebrow="VŠECHNY OBORY" title="Jedno místo pro každou profesi" copy="JdemNaTo! pokrývá český trh zaměstnání, zakázek a služeb — od řemesel po technologie."/><div className="category-grid">{categories.map((c,i)=><Link href={`/obory/${slug(c[0])}`} key={c[0]}><span>{String(i+1).padStart(2,"0")}</span><div><b>{c[0]}</b><small>{c[1]}</small></div><i>→</i></Link>)}</div></section>
      <section className="how"><span className="eyebrow">JEDNODUŠE A FÉROVĚ</span><h2>Jak JdemNaTo! funguje</h2><div>{[["01","Řeknu, co hledám","Práci, zakázku, dodavatele nebo nového zaměstnance."],["02","Porovnám možnosti","Vyberu si podle oboru, místa, podmínek a vlastních preferencí."],["03","Jdu do toho","Ozvu se napřímo. Portál nevybírá za mě a nevstupuje do smlouvy ani platby."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    </main>
    <footer><div className="footer-main"><div><Brand inverse/><p>Práce, zakázky a dodavatelé<br/>na jednom místě.</p></div><div><b>JdemNaTo!</b><Link href="/o-nas">O projektu</Link><Link href="/kontakt">Kontakt</Link><Link href="/podminky">Pravidla</Link></div></div><div className="footer-legal"><span>© 2026 JdemNaTo! Inzertní a vyhledávací portál.</span><div><Link href="/ochrana-osobnich-udaju">Ochrana osobních údajů</Link><Link href="/cookies">Cookies</Link><button onClick={()=>window.dispatchEvent(new Event("jdemnato-cookie-settings"))}>Nastavení cookies</button><Link href="/podminky">Podmínky používání</Link></div></div></footer>
  </>;
}

function Head({eyebrow,title,copy,link,light=false}:{eyebrow:string,title:string,copy?:string,link?:string,light?:boolean}){return <div className="section-head"><div><span className={`eyebrow ${light?"light":""}`}>{eyebrow}</span><h2>{title}</h2></div>{copy&&<p>{copy}</p>}{link&&<Link href={eyebrow.includes("ZAKÁZKU")?"/zakazky":"/prace"}>{link}</Link>}</div>}
function slug(s:string){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}
