"use client";
import { FormEvent, useState } from "react";
type Profile=Record<string,string>|null;type RequestItem=Record<string,string|number>;
const categories=["Řemesla a opravy","Stavby a rekonstrukce","Úklid a správa nemovitostí","IT, weby a software","Marketing a grafika","Účetnictví a finance","Právo a poradenství","Doprava a stěhování","Catering a eventy","Výroba a subdodávky","Energetika a servis","Zdraví, péče a vzdělávání","Ostatní služby"];
function ProfileForm({profile,error,onSubmit,onCancel}:{profile:Profile;error:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;onCancel?:()=>void}){const v=(key:string)=>profile?.[key]||"";return <form className="supplier-register supplier-profile-form rich-profile" onSubmit={onSubmit}><div className="profile-form-head"><div><p className="eyebrow">PROFIL DODAVATELE</p><h2>{profile?"Upravit profil":"Vytvořit profil"}</h2></div>{onCancel&&<button type="button" className="profile-close" onClick={onCancel}>Zavřít</button>}</div>
  <div className="profile-row"><label>Název firmy nebo jméno *<input required name="companyName" defaultValue={v("company_name")}/></label><label>Typ dodavatele *<select required name="supplierType" defaultValue={v("supplier_type")||"Živnostník"}><option>Živnostník</option><option>Firma</option><option>Spolek nebo nezisková organizace</option></select></label></div>
  <div className="profile-row"><label>IČO *<input required name="ico" inputMode="numeric" pattern="[0-9]{8}" defaultValue={v("ico")}/></label><label>Telefon *<input required name="phone" type="tel" defaultValue={v("phone")}/></label></div>
  <div className="profile-row"><label>Sídlo nebo adresa *<input required name="address" defaultValue={v("address")} placeholder="Město, ulice"/></label><label>Web<input name="website" type="url" defaultValue={v("website")} placeholder="https://…"/></label></div>
  <div className="profile-row"><label>Hlavní obor *<select required name="category" defaultValue={v("category")}><option value="">Vyberte obor</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Další služby<input name="otherServices" defaultValue={v("other_services")} placeholder="Např. malování, sádrokarton, úklid"/></label></div>
  <div className="profile-row"><label>Kde působíte? *<input required name="serviceArea" defaultValue={v("service_area")} placeholder="Praha a Středočeský kraj"/></label><label>Maximální dojezd<input name="travelRadius" defaultValue={v("travel_radius")} placeholder="Např. 50 km"/></label></div>
  <div className="profile-row"><label>Dostupnost<input name="availability" defaultValue={v("availability")} placeholder="Např. do 14 dnů"/></label><label>Délka praxe<input name="yearsExperience" defaultValue={v("years_experience")} placeholder="Např. 12 let"/></label></div>
  <div className="profile-row"><label>Velikost týmu<input name="teamSize" defaultValue={v("team_size")} placeholder="Sám / 2–5 lidí / více"/></label><label>Orientační cena<input name="pricing" defaultValue={v("pricing")} placeholder="Od 650 Kč/h nebo dle rozpočtu"/></label></div>
  <label>Oprávnění, certifikáty a kvalifikace<textarea name="credentials" defaultValue={v("credentials")} placeholder="Uveďte pouze platná oprávnění a certifikáty."/></label><label>Pojištění odpovědnosti<input name="insurance" defaultValue={v("insurance")} placeholder="Např. ano, do 5 mil. Kč; údaj následně ověříme"/></label><label>Reference a ukázky realizací<textarea name="referencesText" defaultValue={v("references_text")} placeholder="Stručně popište důležité realizace nebo vložte odkazy."/></label><label>O vás<textarea name="bio" defaultValue={v("bio")} placeholder="Co děláte, jak pracujete a proč si vybrat právě vás?"/></label>
  {error&&<p className="form-error" role="alert">{error}</p>}<button className="primary">{profile?"Uložit změny":"Dokončit registraci zdarma"} →</button><small>Uveďte pouze pravdivé údaje. Profil ani předplatné nezaručují získání zakázky; označení „ověřeno“ přidáme až po skutečné kontrole.</small></form>}
export function SupplierDashboard({email,profile,requests}:{email:string;profile:Profile;requests:RequestItem[]}){const[error,setError]=useState(""),[editing,setEditing]=useState(false),[revealed,setRevealed]=useState<Record<string,{customer_name:string;phone:string;email:string}>>({});async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const response=await fetch("/api/suppliers/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const body=await response.json() as {error?:string};if(!response.ok)return setError(body.error||"Profil se nepodařilo uložit.");location.reload()}async function reveal(id:string){const response=await fetch(`/api/requests/${id}/contact`);const body=await response.json() as {error?:string;customer_name:string;phone:string;email:string};if(!response.ok)return setError(body.error||"Kontakt nelze zobrazit.");setRevealed(x=>({...x,[id]:body}))}
 if(!profile)return <main className="supplier-dashboard"><section className="dashboard-intro"><div><p className="eyebrow">REGISTRACE DODAVATELE</p><h1>Najděte poptávky ve svém oboru</h1><p>Přihlášeni jako {email}. Přístup je během startovacího období zdarma.</p></div></section><ProfileForm profile={null} error={error} onSubmit={save}/></main>;
 return <main className="supplier-dashboard"><section className="dashboard-intro supplier-account-head"><div><p className="eyebrow">ÚČET DODAVATELE</p><h1>{profile.company_name}</h1><p>{profile.category} · {profile.service_area}</p><small>IČO {profile.ico} · {email}</small></div><div className="account-actions"><span className="subscription-badge">✓ Startovací přístup zdarma</span><button className="profile-edit" onClick={()=>setEditing(true)}>Upravit profil</button></div></section>{editing?<ProfileForm profile={profile} error={error} onSubmit={save} onCancel={()=>setEditing(false)}/>:<section className="profile-summary rich-summary"><b>O dodavateli</b><p>{profile.bio||"Doplňte představení svého podnikání."}</p><div><span><b>Služby:</b> {profile.other_services||profile.category}</span><span><b>Dostupnost:</b> {profile.availability||"neuvedena"}</span><span><b>Praxe:</b> {profile.years_experience||"neuvedena"}</span><span><b>Cena:</b> {profile.pricing||"dohodou"}</span></div></section>}{error&&!editing&&<p className="form-error">{error}</p>}
 <section className="request-feed"><div className="section-head"><div><p className="eyebrow">AKTUÁLNÍ POPTÁVKY</p><h2>Zákazníci hledají dodavatele</h2></div><p>Kontakt zobrazte jen tehdy, když chcete opravdu reagovat.</p></div>{requests.length===0?<div className="empty-requests"><h3>Zatím tu nejsou aktivní poptávky.</h3></div>:<div className="request-list">{requests.map(item=><article key={String(item.id)}><div><span>{String(item.category)}</span><h3>{String(item.description)}</h3><p>⌖ {String(item.location)} · termín do {new Date(String(item.needed_by)).toLocaleDateString("cs-CZ")}</p><small>{String(item.budget||"Rozpočet dohodou")} · {String(item.price_type||"Cena dohodou")}</small></div><aside>{revealed[String(item.id)]?<div className="revealed-contact"><small>KONTAKT ZÁKAZNÍKA</small><b>{revealed[String(item.id)].customer_name}</b><a href={`tel:${revealed[String(item.id)].phone}`}>{revealed[String(item.id)].phone}</a><a href={`mailto:${revealed[String(item.id)].email}`}>{revealed[String(item.id)].email}</a></div>:<button className="primary" onClick={()=>reveal(String(item.id))}>Zobrazit kontakt</button>}</aside></article>)}</div>}</section></main>}
