"use client";
import Link from "../ui/SiteLink";
import { FormEvent, useState } from "react";

const groups = ["Řemesla a opravy", "Stavby a rekonstrukce", "Úklid a správa nemovitostí", "IT, weby a software", "Marketing a grafika", "Účetnictví a finance", "Právo a poradenství", "Doprava a stěhování", "Catering a eventy", "Výroba a subdodávky", "Energetika a servis", "Zdraví, péče a vzdělávání"];

export function SupplierRequest() {
  const [manageUrl, setManageUrl] = useState(""); const [type, setType] = useState("");
  const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const form = event.currentTarget, data = new FormData(form);
    const response = await fetch("/api/requests", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ category: type, location: data.get("location"), neededBy: data.get("neededBy"), description: data.get("description"), budget: data.get("budget"), priceType: data.get("priceType"), customerName: data.get("name"), phone: data.get("phone"), email: data.get("email"), consent: data.get("consent") === "on", website: data.get("website") }) });
    const body = await response.json() as { id?: string; managementToken?: string; error?: string };
    if (!response.ok || !body.id || !body.managementToken) return setError(body.error || "Poptávku se nepodařilo uložit.");
    setManageUrl(`${window.location.origin}/poptavka/${body.id}#token=${encodeURIComponent(body.managementToken)}`); form.reset(); setType(""); window.scrollTo({ top: 0, behavior: "smooth" });
  }
  async function copyLink() { await navigator.clipboard.writeText(manageUrl); setCopied(true); }
  if (manageUrl) return <><header className="site-header"><Link href="/" className="brand"><span>Zak</span><strong>ly</strong></Link><nav><Link href="/prace">Hledám práci</Link><Link href="/registrace">Registrace</Link></nav></header><main className="request-done"><section className="request-success"><span>✓</span><div><p className="eyebrow">POPTÁVKA BYLA ODESLÁNA</p><h1>Hotovo. Teď už jen počkáte, kdo se ozve.</h1><p>Výběr dodavatele, cenu, smlouvu i platbu řešíte pouze mezi sebou.</p><div className="management-link"><strong>Uložte si soukromý odkaz pro správu</strong><p>Přes něj můžete poptávku upravit, prodloužit nebo ukončit. Odkaz nikomu neposílejte.</p><input readOnly value={manageUrl}/><button className="primary" onClick={copyLink}>{copied ? "Odkaz zkopírován ✓" : "Zkopírovat odkaz"}</button></div><div className="success-actions"><a className="primary" href={manageUrl}>Spravovat poptávku</a><button className="text-button" onClick={() => { setManageUrl(""); setCopied(false); }}>Zadat další poptávku</button><Link href="/">Zpět na hlavní stránku</Link></div></div></section></main></>;
  return <><header className="site-header"><Link href="/" className="brand"><span>Zak</span><strong>ly</strong></Link><nav><Link href="/prace">Hledám práci</Link><Link href="/dodavatele/seznam">Seznam dodavatelů</Link><Link href="/registrace">Registrace</Link></nav><div className="header-actions"><Link className="ghost" href="/prihlaseni">Přihlásit se</Link></div></header><main className="craft-page request-simple">
    <section className="craft-hero"><p className="eyebrow">HLEDÁM DODAVATELE</p><h1>Popište, co potřebujete.<br/><em>Dodavatelé se vám ozvou.</em></h1><p>Zadání je zdarma a bez registrace. Vy sami si potom porovnáte možnosti a rozhodnete se, koho kontaktujete.</p><div className="craft-steps"><span><b>1</b> Zadáte poptávku</span><span><b>2</b> Dodavatelé se ozvou</span><span><b>3</b> Vyberete si sami</span></div></section>
    <section className="request-panel"><form onSubmit={submit}><input type="text" name="website" tabIndex={-1} autoComplete="off" style={{ position: "absolute", left: "-9999px", width: "1px", height: "1px", opacity: 0 }} aria-hidden="true"/><div className="form-head"><span>ZDARMA · BEZ REGISTRACE</span><h2>Zadat poptávku</h2><p>Povinná pole jsou označena hvězdičkou.</p></div>
      <label>Co hledáte? *<select required value={type} onChange={e => setType(e.target.value)}><option value="">Vyberte obor nebo typ dodavatele</option>{groups.map(g => <option key={g}>{g}</option>)}</select></label>
      <label>Popis zakázky *<textarea required name="description" minLength={20} placeholder="Napište, co přesně potřebujete, přibližný rozsah a další důležité informace."/></label>
      <div className="form-row"><label>Adresa nebo místo zakázky *<input required name="location" autoComplete="street-address" placeholder="Např. Praha 7 nebo práce na dálku"/></label><label>Potřebuji nejpozději do *<input required name="neededBy" type="date"/></label></div>
      <div className="form-row"><label>Orientační rozpočet<input name="budget" placeholder="Např. do 30 000 Kč nebo dohodou"/></label><label>Způsob nacenění<select name="priceType" defaultValue="Cena dohodou"><option>Cena dohodou</option><option>Pevná cena za celé dodání</option><option>Hodinová sazba</option><option>Rozpočet po položkách</option><option>Měsíční paušál</option></select></label></div>
      <fieldset className="contact-fields"><legend>Kontaktní údaje</legend><p>Tyto údaje nejsou veřejné. Zobrazí se pouze přihlášeným dodavatelům s oprávněním odpovídat.</p><div className="form-row"><label>Jméno *<input required name="name" autoComplete="name" placeholder="Jan Novák"/></label><label>Telefon *<input required name="phone" type="tel" autoComplete="tel" placeholder="+420 777 123 456"/></label></div><label>E-mail *<input required name="email" type="email" autoComplete="email" placeholder="jan@priklad.cz"/></label><label className="contact-consent"><input required name="consent" type="checkbox"/> Souhlasím s předáním kontaktu přihlášeným dodavatelům za účelem vyřízení této poptávky. *</label></fieldset>
      {error && <p className="form-error" role="alert">{error}</p>}<button className="primary submit">Zveřejnit poptávku zdarma →</button><small>Odesláním nevzniká povinnost někoho vybrat ani objednat. Zakly neurčuje cenu, nevybírá dodavatele a nepřijímá platbu za zakázku.</small>
    </form></section><section className="supplier-entry"><div><p className="eyebrow">JSTE DODAVATEL?</p><h2>Chcete odpovídat zákazníkům?</h2><p>Vytvořte si dodavatelský profil. Během startovacího období je přístup ke kontaktům zdarma; budoucí předplatné spustíme až po předchozím oznámení.</p></div><Link className="primary" href="/registrace">Registrovat dodavatele →</Link></section>
  </main></>;
}
